# Configuration for training on TinyStories dataset
# TinyStories is a collection of short stories generated by GPT-3.5
# Dataset: https://huggingface.co/datasets/roneneldan/TinyStories

# I/O
out_dir = 'out-tinystories'
eval_interval = 500
eval_iters = 100

# data
dataset = 'tinystories'
gradient_accumulation_steps = 8  # used to simulate larger batch sizes
batch_size = 8  # if gradient_accumulation_steps > 1, this is the micro-batch size
block_size = 1024

# model (GPT-2 size: 124M parameters)
n_layer = 12
n_head = 12
n_embd = 768
dropout = 0.0

# adamw optimizer
learning_rate = 3e-4
max_iters = 20000  # Total training iterations
weight_decay = 1e-1
beta1 = 0.9
beta2 = 0.95

# learning rate decay settings
warmup_iters = 200
lr_decay_iters = 20000
min_lr = 6e-5

# system
dtype = 'bfloat16'
compile = True
