# saves the TinyStories dataset to a binary file for training
# TinyStories is a dataset of short stories generated by GPT-3.5
# Available at: https://huggingface.co/datasets/roneneldan/TinyStories

import os
from tqdm import tqdm
import numpy as np
import tiktoken
from datasets import load_dataset  # huggingface datasets

# number of workers in .map() call
num_proc = 8

# number of workers in load_dataset() call
num_proc_load_dataset = num_proc

enc = tiktoken.get_encoding("gpt2")

if __name__ == '__main__':
    # Load TinyStories dataset from Hugging Face
    print("Loading TinyStories dataset...")
    dataset = load_dataset("roneneldan/TinyStories", split="train", num_proc=num_proc_load_dataset)
    
    # Create train/val split (use 95/5 split for more training data)
    split_dataset = dataset.train_test_split(test_size=0.05, seed=2357, shuffle=True)
    split_dataset['val'] = split_dataset.pop('test')  # rename test to val

    print("Dataset split created:")
    print(f"  train: {len(split_dataset['train'])} examples")
    print(f"  val: {len(split_dataset['val'])} examples")

    # Define tokenization function
    def process(example):
        ids = enc.encode_ordinary(example['text'])  # encode_ordinary ignores any special tokens
        ids.append(enc.eot_token)  # add the end of text token (50256 for gpt2 bpe)
        out = {'ids': ids, 'len': len(ids)}
        return out

    # Tokenize the dataset
    print("Tokenizing dataset...")
    tokenized_train = split_dataset['train'].map(
        process, remove_columns=['text'], desc="tokenizing train", num_proc=num_proc
    )
    tokenized_val = split_dataset['val'].map(
        process, remove_columns=['text'], desc="tokenizing val", num_proc=num_proc
    )

    # More efficient approach: pre-allocate array and fill it
    print("Writing tokens to binary files...")
    
    # Process train split
    train_len = sum(tokenized_train['len'])
    print(f"train will have {train_len:,} tokens")
    train_ids = np.memmap(os.path.join(os.path.dirname(__file__), 'train.bin'), 
                          dtype=np.uint16, mode='w+', shape=(train_len,))
    idx = 0
    for token_ids in tqdm(tokenized_train['ids'], desc='writing train'):
        train_ids[idx : idx + len(token_ids)] = token_ids
        idx += len(token_ids)
    train_ids.flush()
    
    # Process val split
    val_len = sum(tokenized_val['len'])
    print(f"val will have {val_len:,} tokens")
    val_ids = np.memmap(os.path.join(os.path.dirname(__file__), 'val.bin'), 
                        dtype=np.uint16, mode='w+', shape=(val_len,))
    idx = 0
    for token_ids in tqdm(tokenized_val['ids'], desc='writing val'):
        val_ids[idx : idx + len(token_ids)] = token_ids
        idx += len(token_ids)
    val_ids.flush()
    
    # Save metadata
    meta = {
        'vocab_size': enc.n_vocab,
        'tokenizer': 'gpt2'
    }
    import pickle
    with open(os.path.join(os.path.dirname(__file__), 'meta.pkl'), 'wb') as f:
        pickle.dump(meta, f)

    print(f"Done! Files saved to {os.path.dirname(__file__)}")
